image: alpine

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  ECR: 225237029829.dkr.ecr.eu-west-2.amazonaws.com
  IMAGE: trunarrative/alpine
  REGION: eu-west-2

services:
  - docker:dind

stages:
  - build-base
  - build-others

.build:
  stage: build-others
  before_script:
    - apk update
    - apk add docker py3-pip jq
    - pip3 install -U pip
    - pip3 install awscli
    - $(aws ecr get-login --no-include-email --region $REGION)
    - docker login --username $(aws secretsmanager get-secret-value --secret-id 'dockerhub-username' --output json --region eu-west-2 | jq -r '.SecretString') --password $(aws secretsmanager get-secret-value --secret-id 'dockerhub-password' --output json --region $REGION | jq -r '.SecretString')
  script:
    - docker build -t "${ECR}/${IMAGE}:${CI_JOB_NAME}" "$CI_JOB_NAME"
    - docker push "${ECR}/${IMAGE}:${CI_JOB_NAME}"
    - docker push "${IMAGE}:${CI_JOB_NAME}"
base:
  extends: .build
  stage: build-base

infra:
  extends: .build

qa:
  extends: .build

latest:
  extends: .build
