image: alpine

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE: 225237029829.dkr.ecr.eu-west-2.amazonaws.com/trunarrative/alpine

services:
  - docker:dind

stages:
  - build-base
  - build-others

.build:
  stage: build-others
  before_script:
    - apk update
    - apk add docker
  script:
    - docker build -t "${IMAGE}:${CI_JOB_NAME}" "$CI_JOB_NAME"

base:
  extends: .build
  stage: build-base

infra:
  extends: .build

qa:
  extends: .build

latest:
  extends: .build
